<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Room;

class RoomsTableSeeder extends Seeder
{
    public function run()
    {
        $rooms = [
            [
                'name' => 'Sala FEN 1',
                'location' => 'Edificio FEN, Piso 1',
                'capacity' => 35,
                'description' => 'Sala principal equipada con proyector HD, sistema de audio, aire acondicionado y pizarra interactiva. Ideal para clases magistrales y presentaciones.',
                // Equipamiento completo y en buen estado
                'calefaccion' => true,
                'energia_electrica' => true,
                'existe_aseo' => true,
                'plumones' => true,
                'borrador' => true,
                'pizarra_limpia' => true,
                'computador_funcional' => true,
                'cables_computador' => true,
                'control_remoto_camara' => true,
                'televisor_funcional' => true,
            ],
            [
                'name' => 'Sala FEN 2',
                'location' => 'Edificio FEN, Piso 1',
                'capacity' => 30,
                'description' => 'Sala estándar para clases de postgrado con proyector, sistema de audio básico y climatización. Configuración flexible de mobiliario.',
                'calefaccion' => true,
                'energia_electrica' => true,
                'existe_aseo' => true,
                'plumones' => true,
                'borrador' => true,
                'pizarra_limpia' => true,
                'computador_funcional' => true,
                'cables_computador' => true,
                'control_remoto_camara' => false,
                'televisor_funcional' => true,
            ],
            [
                'name' => 'Sala FEN 3',
                'location' => 'Edificio FEN, Piso 2',
                'capacity' => 28,
                'description' => 'Sala multimedia con pantalla de proyección, sistema de videoconferencia y conexión HDMI. Óptima para clases híbridas.',
                'calefaccion' => true,
                'energia_electrica' => true,
                'existe_aseo' => false,
                'plumones' => true,
                'borrador' => true,
                'pizarra_limpia' => false,
                'computador_funcional' => true,
                'cables_computador' => true,
                'control_remoto_camara' => true,
                'televisor_funcional' => true,
            ],
            [
                'name' => 'Sala de Computación',
                'location' => 'Edificio FEN, Piso 1',
                'capacity' => 25,
                'description' => 'Laboratorio equipado con 25 computadores de escritorio, software especializado (SPSS, Stata, R), red cableada de alta velocidad y proyector.',
                'calefaccion' => true,
                'energia_electrica' => true,
                'existe_aseo' => true,
                'plumones' => false,
                'borrador' => false,
                'pizarra_limpia' => true,
                'computador_funcional' => true,
                'cables_computador' => true,
                'control_remoto_camara' => false,
                'televisor_funcional' => true,
            ],
            [
                'name' => 'Auditorio FEN',
                'location' => 'Edificio FEN, Piso 1',
                'capacity' => 120,
                'description' => 'Auditorio principal con capacidad para 120 personas, sistema de audio profesional, proyección dual, transmisión en vivo y butacas fijas.',
                'calefaccion' => true,
                'energia_electrica' => true,
                'existe_aseo' => true,
                'plumones' => true,
                'borrador' => true,
                'pizarra_limpia' => true,
                'computador_funcional' => true,
                'cables_computador' => true,
                'control_remoto_camara' => true,
                'televisor_funcional' => false, // Usa proyector
            ],
            [
                'name' => 'Sala de Reuniones Decanato',
                'location' => 'Edificio FEN, Piso 3',
                'capacity' => 12,
                'description' => 'Sala ejecutiva para reuniones administrativas y académicas. Equipada con mesa de reuniones, TV 55", sistema de videoconferencia y climatización.',
                'calefaccion' => true,
                'energia_electrica' => true,
                'existe_aseo' => true,
                'plumones' => true,
                'borrador' => true,
                'pizarra_limpia' => true,
                'computador_funcional' => false,
                'cables_computador' => true,
                'control_remoto_camara' => true,
                'televisor_funcional' => true,
            ],
            [
                'name' => 'Arrayán 1',
                'location' => 'Laboratorio de Ingeniería Informática Empresarial',
                'capacity' => 12,
                'description' => 'Sala de trabajo colaborativo con 12 estaciones de trabajo, pantalla de proyección y conexión a impresora de red.',
                'calefaccion' => false,
                'energia_electrica' => true,
                'existe_aseo' => false,
                'plumones' => false,
                'borrador' => false,
                'pizarra_limpia' => false,
                'computador_funcional' => true,
                'cables_computador' => true,
                'control_remoto_camara' => false,
                'televisor_funcional' => false,
            ],
            [
                'name' => 'Arrayán 2',
                'location' => 'Laboratorio de Ingeniería Informática Empresarial',
                'capacity' => 30,
                'description' => 'Laboratorio principal con 30 computadores, software de desarrollo, impresoras multifuncionales y escáner. Ideal para talleres prácticos.',
                'calefaccion' => true,
                'energia_electrica' => true,
                'existe_aseo' => true,
                'plumones' => true,
                'borrador' => true,
                'pizarra_limpia' => true,
                'computador_funcional' => true,
                'cables_computador' => true,
                'control_remoto_camara' => false,
                'televisor_funcional' => true,
            ],
            [
                'name' => 'Arrayán 3',
                'location' => 'Laboratorio de Ingeniería Informática Empresarial',
                'capacity' => 22,
                'description' => 'Sala híbrida con 22 puestos, sistema de videoconferencia integrado, pizarra digital y conexión de red redundante.',
                'calefaccion' => true,
                'energia_electrica' => true,
                'existe_aseo' => false,
                'plumones' => true,
                'borrador' => true,
                'pizarra_limpia' => true,
                'computador_funcional' => true,
                'cables_computador' => true,
                'control_remoto_camara' => true,
                'televisor_funcional' => true,
            ],
            [
                'name' => 'Sala de Estudio Postgrado',
                'location' => 'Edificio FEN, Piso 2',
                'capacity' => 15,
                'description' => 'Sala de estudio exclusiva para estudiantes de postgrado. Cuenta con mesas de trabajo, conexión eléctrica en todos los puestos y WiFi de alta velocidad.',
                'calefaccion' => true,
                'energia_electrica' => true,
                'existe_aseo' => false,
                'plumones' => false,
                'borrador' => false,
                'pizarra_limpia' => true,
                'computador_funcional' => false,
                'cables_computador' => false,
                'control_remoto_camara' => false,
                'televisor_funcional' => false,
            ]
        ];

        foreach ($rooms as $roomData) {
            Room::firstOrCreate(
                ['name' => $roomData['name']],
                $roomData
            );
        }

        $this->command->info("✅ Salas creadas con equipamiento realista y detallado.");
    }
}
